baseURL: http://spiffworkflow.org/
languageCode: en-us
title: SpiffWorkflow
theme: fresh
googleAnalytics: G-3Z83G8WLEK
privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    disable: false
    respectDoNotTrack: true

# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description: Homepage for SpiffWorkflow and SpiffArena - open source projects which seek to improve transparency and understanding in organizations through intuitive executable diagrams.  These projects are based on the OMG's BPMN and DMN standards.
  # Preloader ensures images are loaded before displaying to the user. If you don't want it uncomment to set it to false
  # preloader: false
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/spiffworkflow_logo.png
    link: /
    # Default width/height. Uncomment if you need to change
    width: 138
    height: 28
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Executable Diagrams
    # Hero subtitle (optional)
    subtitle: Connect people and software together in a way that makes sense to everyone.
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "/posts/articles/get_started"
    # Hero image (from static/images/___)
    image: illustrations/flow.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
    - status
    - uva
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Features
    url: /pages/features
  - title: Projects
    sublinks:
      - title: SpiffWorkflow
        url: /pages/spiffworkflow
      - title: SpiffArena
        url: /pages/spiffarena
      - title: SpiffEditor
        url: /pages/spiffeditor
  - title: Articles
    sublinks:
      - title: Introductory Articles
        url: /posts/articles
      - title: Deep Dives
        url: /posts/deep_dives
  - title: Support
    url: /pages/support
    button: true
  sidebar:
    # Logo (from /images/logos/___.svg)
    logo: spiffworkflow_white
    sections:
    - title: Projects
      icon: user
      links:
      - text: SpiffWorkflow
        url: /pages/spiffworkflow
      - text: SpiffArena
        url: /pages/spiffarena
      - text: SpiffEditor
        url: /pages/spiffeditor
    - title: Articles
      icon: envelope
      links:
      - text: Introductory Articles
        url: /posts/articles
      - text: Deep Dive Articles
        url: /posts/deep_dives
  section1:
    title: Open Source Software
    subtitle:  It's all open.  All of it. The whole enchilada. (Well it would be a tostada then, wouldn't it?)
    tiles:
    - title: SpiffWorkflow
      icon: spiffworkflow
      text: The original lightweight diagram execution library.
      url: /pages/spiffworkflow
      buttonText: Learn More
    - title: SpiffArena
      icon: spiffarena
      text: A complete platform for managing diagrams.
      url: /pages/spiffarena
      buttonText: Learn More
    - title: SpiffEditor
      icon: spiffedit
      text: Extensions for the popular BPMN.io diagram editor.
      url: /pages/spiffeditor
      buttonText: Learn More
  section2:
    title: It's about people
    subtitle: We bet the future is not about monitizing people using automated systems.  We believe in a future filled with human innovation that is supported by software that increases transparency, understanding, and collaboration.
    features:
    - title: Create Transparency
      text: Only when people understand processes will they contribute to their improvement.  Executable diagrams allow people to see what is happening behind the curtains.  The benefit of transparency is twofold&colon;  it creates empathy ("I didn't know you were handling so much!") and it provides power ("Hey, if we reviewed this earlier it would save everyone a lot of time").
      icon: transparency
    - title: Automate The Bots
      text: No one wants 20 applications telling them what to do all day.  In many cases, what we need is a little glue -- a way to pull information from one system and use it in another.  The Service Tasks in our diagrams allows us to talk to services, gather information, send that information to other services, getting ourselves out of the loop.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: bots
    - title: Deliver on Schedule
      text: Computers make great clock watchers, so let them do it.  We need more time by the fireplace for contemplation and less time responding to our endlessly beeping phones with their often pointless interruptions.    If we can reduce the noise and think in peace, then perhaps we can do something of merit, of consequence -- something worthy of our precious time.
      icon: clock
  section3:
    title: Intuitive Diagrams
    subtitle: Diagrams can be intuitive AND executable - removing monotony, adding transparency and opening opportunities for improvement and adaptation.
    image: illustrations/school.svg
    buttonText: Features
    buttonLink: "/pages/features"
  section4:
    title: Join the Innovators
    subtitle: We are just getting started.  Join these innovators and help us continue to refine and improve this important open source project.
    clients:
    - name: Jarrad Hope
      quote: Absolutely amazing work, thank you so very much for pulling off the MVP, it's exactly what I was hoping for and really appreciate working with you guys...
      job: CoFounder - Status.im
      img: jarrad
    - name: Ron Hutchins
      quote: You guys are rock stars. I really appreciate your passion and your expertise on this project. I’m very excited too about what we can do with it in the future.
      job: VP - IT - UVA
      img: ron
  section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: spiffworkflow_white.svg
    # Social Media Title
    socialmediatitle: Connect
    # Social media links (GitHub, Twitter, etc.). All are optional./
    socialmedia:
    - link: https://discord.gg/F6Kb7HNK7B
      icon: comments
    - link: https://github.com/sartography
      # Icons are from Font Awesome
      icon: github
    - link: https://www.youtube.com/channel/UCtDHzDfhyvnAb8CFmdwucUA
      icon: youtube
    - link: https://twitter.com/SpiffWorkflow
      icon: twitter
    - link: https://spiffworkflow.readthedocs.io/en/latest/index.html
      icon: book
    bulmalogo: false
    quicklinks:
      column1:
        title: "Projects"
        links:
        - text: SpiffArena
          link: /pages/spiffarena
        - text: SpiffWorkflow
          link: /pages/spiffworkflow
        - text: SpiffEditor
          link: /pages/spiffeditor
      column2:
        title: "Docs"
        links:
        - text: Get started
          link: /posts/articles/get_started
      column3:
        title: "Blog"
        links:
        - text: Introductory Articles
          link: /posts/articles
        - text: Deep Dives
          link: /posts/deep_dives
