baseURL: https://www.spiffworkflow.org/
languageCode: en-us
title: SpiffWorkflow
theme: fresh
privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    disable: false
    respectDoNotTrack: true

# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  images:
  - /images/opengraph/home.png
  # Used as meta data; describe your site to make Google Bots happy
  description: Business Process Automation with BPMN and Python.  Connect people and software together in a way that makes sense to everyone.
  # Preloader ensures get_started are loaded before displaying to the user. If you don't want it uncomment to set it to false
  # preloader: false
  navbarlogo:
  # Logo (from static/get_started/logos/___)
    image: logos/spiffworkflow_logo.png
    link: /
    # Default width/height. Uncomment if you need to change
    width: 138
    height: 28
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Process Automation with BPMN and Python
    # Hero subtitle (optional)
    subtitle: Connect people and software together in a way that makes sense to everyone.
    # Button text
    buttontext: Available Now at SpiffWorks
    # Where the main hero button links to
    buttonlink: "https://spiff.works"
    buttonid: "spiff-works"
    # Hero image (from static/get_started/___)
    image: illustrations/intro.png
    # Footer logos (from static/get_started/logos/clients/___.svg)
    clientlogos:
    - status
    - uva
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Get Started
    url: /pages/get_started/
  - title: Features
    url: /pages/features/
  - title: Comparison
    url: /pages/compare/
  - title: Support
    url: /pages/support/
  - title: Documentation
    url: /pages/docs/
  section1:
    title: A Powerful Low Code Platform
    subtitle: Build your first diagram in minutes. But don't let the simplicity fool you. SpiffWorkflow is a powerful platform that can handle the most complex of business processes.
    image: build_a_diagram.gif
    buttonText: View Full Video
    buttonLink: https://www.youtube.com/watch?v=876q2s5fwUY&t=1s
  contact: true
  science:
    title: Case Study
    subtitle: Featured in IEEE Software, Jan 2023
    quotes:
    - quote: "How our software development team used an open source Python library and the popular modeling notation, BPMN, to shed light on a set of complex approval processes at a university."
      citation: "D. Funk, \"Creating a Low-Code Business Process Execution Platform With Python, BPMN, and DMN,\" in IEEE Software, vol. 40, no. 1, pp. 9-17, Jan.-Feb. 2023, doi: 10.1109/MS.2022.3212033."
      image: /images/ieee.png
      link: /ieee_spiffworkflow_article.pdf
      buttonText: View PDF
  science2:
    title: Listen to the Pod Cast
    subtitle: Featured on The Real Python Podcast, Feburary 2023
    quotes:
      - quote: "We discuss the concept of low-code software tools. Dan also talks about how SpiffWorkflow aims at getting non-developers within an organization involved in development."
        citation: "The Real Python Podcast with Christopher Bailey, February 2023"
        image: /images/podcast.avif
        link: https://realpython.com/podcasts/rpp/144/
        buttonText: Listen Now
  section2:
    title: A Thriving Open Source Community
    subtitle: We are open source, releasing much of our software under the LGPLv3.  We welcome contributions from the community and are happy to help you get started.  We make contributions to the open source community on a daily basis.
    features:
    - title: 1800+ Stars
      text: Continuous growth and usage for over a decade, with a thriving community of contributors.
      icon: star-history.png
    - title: 40+ Contributors
      text: Contributors from across the world, from the States, Germany, Sweden, South America, the Netherlands, and more.
      # Icon (from /get_started/illustrations/icons/___.svg)
      icon: contributors.png
    - title: 500+ Discord Members
      text: A growing community of users and contributors, with a dedicated Discord server, and regular community calls and AMAs.
      icon: discord.png
  section4:
    title: Join the Innovators
    subtitle: Join these innovators and help us continue to refine and improve this important open source project.
    clients:
    - name: Jarrad Hope
      quote: I’m proud of our investment in SpiffWorkflow. It’s in line with our mission and core principles of purposeful technology, public good, and openness. I am excited about the future and looking forward to working with you.
      job: CoFounder - Status.im
      img: jarrad
    - name: Ron Hutchins
      quote: You guys are rock stars. I really appreciate your passion and your expertise on this project. I’m very excited too about what we can do with it in the future.
      job: VP - IT - UVA
      img: ron
    - name: Demetrick Ferguson
      quote: Organizations large and small need SpiffWorkflow! SpiffWorkflow makes it possible to execute adaptable business processes that more than one person, more than one department, can understand.
      job: Portfolio Performance and Governance - Status
      img: demetrick
    - name: Brian
      quote: Spiffworkflow streamlines our execution of BPMN workflows, and its extensibility is a boon for us. The authors’ willingness to respond to our inquiries and feedback further enriches our experience with the library.
      job: CTO - Series C Startup
      img: brian2
    - name: Aleksandra Yarokhovich
      quote: Collaborating on the SpiffWorkflow project has been a delight. Passionate team, open to ideas, and a powerful product combining BPMN with Python's agility. Best wishes for its success!
      job: Business Analyst - Status
      img: sasha
    - name: Rajat Roy
      quote: We are using spiff workflow in our serverless travel booking engine. It allows us rapid change of business logic with minimum development effort, and in the long run to improve the maintainability thanks to the graphical visualisation.
      job: Software Engineer
      img: rajat
  section5:
    title: Ready To Go SpiffWorkflow
    subtitle: A Hosted and managed instance of SpiffWorkflow is now available at SpiffWorks.  We have everything you need to get started
      quickly.  We will be there to help you build your first diagram and integrate SpiffWorkflow into your existing organization.
    tiles:
      - title: SpiffWorks
        icon: spiffworks
        text: Let us set up and host SpiffWorkflow for you.  We can help you get started, and provide ongoing support and maintenance.
        url: https://spiff.works
        buttonText: Learn More
        class: tile-secondary
  section6: false
  newsletter: true
  footer:
    # Logo (from /get_started/logos/___)
    logo: spiffworkflow_white.svg
    # Social Media Title
    socialmediatitle: Connect
    # Social media links (GitHub, Twitter, etc.). All are optional./
    socialmedia:
    - link: https://discord.gg/F6Kb7HNK7B
      icon: comments
    - link: https://github.com/sartography
      # Icons are from Font Awesome
      icon: github
    - link: https://www.youtube.com/channel/UCtDHzDfhyvnAb8CFmdwucUA
      icon: youtube
    - link: https://twitter.com/SpiffWorkflow
      icon: twitter
    - link: https://spiffworkflow.readthedocs.io/en/latest/index.html
      icon: book
    bulmalogo: false
    quicklinks:
      column1:
        title: "Videos"
        links:
          - text: Building Web Forms
            link: https://www.youtube.com/watch?v=1IaiaquQ0y0&t=15s
          - text: Brief Demo
            link: https://www.youtube.com/watch?v=876q2s5fwUY&t=1s
          - text: Building an Approval Process
            link: https://www.youtube.com/watch?v=EfTbTg3KRqc
          - text: more videos...
            link: https://www.youtube.com/channel/UCtDHzDfhyvnAb8CFmdwucUA
      column2:
        title: "Docs"
        links:
        - text: SpiffWorkflow Application
          link: https://spiff-arena.readthedocs.io/en/latest/
        - text: SpiffWorkflow Library
          link: https://spiffworkflow.readthedocs.io/en/latest/
        - text: Privacy Policy
          link: /pages/privacy_policy/
        - text: Terms of Service
          link: /pages/demo_terms_of_service/
        - text: Service Level Expectations
          link: /pages/service_level/
      column3:
        title: "Blog"
        links:
        - text: Get started
          link: /posts/articles/get_started/
        - text: Introductory Articles
          link: /posts/articles/
        - text: Deep Dives
          link: /posts/deep_dives/
