baseURL: https://www.spiffworkflow.org/
languageCode: en-us
title: SpiffWorkflow
theme: fresh
privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    disable: false
    respectDoNotTrack: true

# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  images:
  - /images/favicon.png
  - /images/default_thumbnail.png
  # Used as meta data; describe your site to make Google Bots happy
  description: Business Process Automation with BPMN and Python.  Connect people and software together in a way that makes sense to everyone.
  # Preloader ensures get_started are loaded before displaying to the user. If you don't want it uncomment to set it to false
  # preloader: false
  navbarlogo:
  # Logo (from static/get_started/logos/___)
    image: logos/spiffworkflow_logo.png
    link: /
    # Default width/height. Uncomment if you need to change
    width: 138
    height: 28
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Process Automation with BPMN and Python
    # Hero subtitle (optional)
    subtitle: Connect people and software together in a way that makes sense to everyone.
    # Button text
    buttontext: Try it now!
    # Where the main hero button links to
    buttonlink: "/posts/articles/get_started/"
    # Hero image (from static/get_started/___)
    image: illustrations/flow.svg
    # Footer logos (from static/get_started/logos/clients/___.svg)
    clientlogos:
    - status
    - uva
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Features
    url: /pages/features/
  - title: Support
    url: /pages/support/
  - title: Projects
    sublinks:
      - title: SpiffWorkflow
        url: /pages/spiffworkflow/
      - title: SpiffArena
        url: /pages/spiffarena/
      - title: SpiffEditor
        url: /pages/spiffeditor/
  - title: Articles
    sublinks:
      - title: Introductory Articles
        url: /posts/articles/
      - title: Deep Dives
        url: /posts/deep_dives/
  sidebar:
    # Logo (from /get_started/logos/___.svg)
    logo: spiffworkflow_white
    sections:
    - title: Projects
      icon: user
      links:
      - text: SpiffWorkflow
        url: /pages/spiffworkflow/
      - text: SpiffArena
        url: /pages/spiffarena/
      - text: SpiffEditor
        url: /pages/spiffeditor/
    - title: Articles
      icon: envelope
      links:
      - text: Introductory Articles
        url: /posts/articles/
      - text: Deep Dive Articles
        url: /posts/deep_dives/
  section1:
    title: Open Source Software
    subtitle:  It's all open.  All of it. The whole enchilada. (Well it would be a tostada then, wouldn't it?)
    tiles:
    - title: SpiffWorkflow
      icon: spiffworkflow
      text: The original lightweight diagram execution library.
      url: /pages/spiffworkflow/
      buttonText: Learn More
      class: tile-secondary
    - title: SpiffArena
      icon: spiffarena
      text: A complete platform for managing diagrams.
      url: /pages/spiffarena/
      buttonText: Learn More
      class: tile-primary
    - title: SpiffEditor
      icon: spiffedit
      text: Extensions for the popular BPMN.io diagram editor.
      url: /pages/spiffeditor/
      buttonText: Learn More
      class: tile-secondary
  section2:
    title: Empower Your People
    subtitle: We bet the future is not about monetizing people using automated systems.  We believe in a future filled with human innovation that is supported by software that increases transparency, understanding, and collaboration.
    features:
    - title: Create Transparency
      text: Only when people understand processes will they contribute to their improvement.  Executable diagrams allow people to see what is happening behind the curtains.  The benefit of transparency is twofold&colon;  it creates empathy ("I didn't know you were handling so much!") and it provides power ("Hey, if we reviewed this earlier it would save everyone a lot of time").
      icon: transparency
    - title: Automate The Bots
      text: No one wants 20 applications telling them what to do all day.  In many cases, what we need is a little glue -- a way to pull information from one system and use it in another.  The Service Tasks in our diagrams allows us to talk to services, gather information, send that information to other services, getting ourselves out of the loop.
      # Icon (from /get_started/illustrations/icons/___.svg)
      icon: bots
    - title: Deliver on Schedule
      text: Computers make great clock watchers, so let them do it.  We need more time by the fireplace for contemplation and less time responding to our endlessly beeping phones with their often pointless interruptions.    If we can reduce the noise and think in peace, then perhaps we can do something of merit, of consequence -- something worthy of our precious time.
      icon: clock
  section3:
    title: A Powerful Low Code Platform
    subtitle: Excellent tools may take time to master, but in the right hands yield exceptional results. This is a tool for professionals and scientists.  We do not offer paint by numbers coloring books. We do not have any crayons.
    image: illustrations/school.svg
    buttonText: Features
    buttonLink: "/pages/features/"
  section4:
    title: Join the Innovators
    subtitle: Join these innovators and help us continue to refine and improve this important open source project.
    clients:
    - name: Jarrad Hope
      quote: I’m proud of our investment in SpiffWorkflow. It’s in line with our mission and core principles of purposeful technology, public good, and openness. I am excited about the future and looking forward to working with you.
      job: CoFounder - Status.im
      img: jarrad
    - name: Ron Hutchins
      quote: You guys are rock stars. I really appreciate your passion and your expertise on this project. I’m very excited too about what we can do with it in the future.
      job: VP - IT - UVA
      img: ron
    - name: Demetrick Ferguson
      quote: Organizations large and small need SpiffWorkflow! SpiffWorkflow makes it possible to execute adaptable business processes that more than one person, more than one department, can understand.
      job: Portfolio Performance and Governance - Status
      img: demetrick
  section5: true
  section6: true
  footer:
    # Logo (from /get_started/logos/___)
    logo: spiffworkflow_white.svg
    # Social Media Title
    socialmediatitle: Connect
    # Social media links (GitHub, Twitter, etc.). All are optional./
    socialmedia:
    - link: https://discord.gg/F6Kb7HNK7B
      icon: comments
    - link: https://github.com/sartography
      # Icons are from Font Awesome
      icon: github
    - link: https://www.youtube.com/channel/UCtDHzDfhyvnAb8CFmdwucUA
      icon: youtube
    - link: https://twitter.com/SpiffWorkflow
      icon: twitter
    - link: https://spiffworkflow.readthedocs.io/en/latest/index.html
      icon: book
    bulmalogo: false
    quicklinks:
      column1:
        title: "Projects"
        links:
        - text: SpiffArena
          link: /pages/spiffarena/
        - text: SpiffWorkflow
          link: /pages/spiffworkflow/
        - text: SpiffEditor
          link: /pages/spiffeditor/
      column2:
        title: "Docs"
        links:
        - text: Privacy Policy
          link: /pages/privacy_policy/
        - text: Terms of Service
          link: /pages/demo_terms_of_service/
        - text: Service Level Expectations
          link: /pages/service_level/
      column3:
        title: "Blog"
        links:
        - text: Get started
          link: /posts/articles/get_started/
        - text: Introductory Articles
          link: /posts/articles/
        - text: Deep Dives
          link: /posts/deep_dives/
