baseURL: https://www.spiffworkflow.org/
languageCode: en-us
title: SpiffWorkflow
theme: fresh
privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    disable: false
    respectDoNotTrack: true

# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  images:
  - /images/favicon.png
  - /images/default_thumbnail.png
  # Used as meta data; describe your site to make Google Bots happy
  description: Business Process Automation with BPMN and Python.  Connect people and software together in a way that makes sense to everyone.
  # Preloader ensures get_started are loaded before displaying to the user. If you don't want it uncomment to set it to false
  # preloader: false
  navbarlogo:
  # Logo (from static/get_started/logos/___)
    image: logos/spiffworkflow_logo.png
    link: /
    # Default width/height. Uncomment if you need to change
    width: 138
    height: 28
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Process Automation with BPMN and Python
    # Hero subtitle (optional)
    subtitle: Connect people and software together in a way that makes sense to everyone.
    # Button text
    buttontext: Try it now!
    # Where the main hero button links to
    buttonlink: "/posts/articles/get_started/"
    # Hero image (from static/get_started/___)
    image: illustrations/flow.svg
    # Footer logos (from static/get_started/logos/clients/___.svg)
    clientlogos:
    - status
    - uva
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Features
    url: /pages/features/
  - title: Support
    url: /pages/support/
  - title: Projects
    sublinks:
      - title: SpiffWorkflow
        url: /pages/spiffworkflow/
      - title: SpiffArena
        url: /pages/spiffarena/
      - title: SpiffEditor
        url: /pages/spiffeditor/
  - title: Articles
    sublinks:
      - title: Introductory Articles
        url: /posts/articles/
      - title: Deep Dives
        url: /posts/deep_dives/
  sidebar:
    # Logo (from /get_started/logos/___.svg)
    logo: spiffworkflow_white
    sections:
    - title: Projects
      icon: user
      links:
      - text: SpiffWorkflow
        url: /pages/spiffworkflow/
      - text: SpiffArena
        url: /pages/spiffarena/
      - text: SpiffEditor
        url: /pages/spiffeditor/
    - title: Articles
      icon: envelope
      links:
      - text: Introductory Articles
        url: /posts/articles/
      - text: Deep Dive Articles
        url: /posts/deep_dives/
  section1:
    title: Commercial Support
    subtitle:  We offer commercial support for SpiffWorkflow and related projects.  We can help you with everything from getting started, to building your first diagram, to integrating SpiffWorkflow into your existing systems.
    tiles:
    - title: Training
      icon: training
      text: From BPMN to Dev-Ops we offer training to get you moving quickly and to assure you getting the most out of your investment.
      url: /pages/training/
      buttonText: Learn More
      class: tile-secondary
    - title: Hosting
      icon: hosting
      text: Let us set up and host SpiffWorkflow for you.  We can help you get started, and provide ongoing support and maintenance.
      url: /pages/hosting/
      buttonText: Learn More
      class: tile-secondary
    - title: Integration
      icon: enterprise
      text: Enterprise level integrations for Authentication, pre-built reusable workflows, and connectors to rest of your enterprise systems.
      url: /pages/enterprise/
      buttonText: Learn More
      class: tile-secondary
  science:
    title: Grounded in Science
    subtitle: We have combined the most heavily researched standard in the field of Business Process Automation with the most popular programming language in the world(1).
    tiles:
      - title: BPMN
        icon: bpmn
        text: 1000's of articles on the efficacy of BPMN in diverse domains from Health Care(3) to Lagistics(4) to Automotive(5).
        class: tile-secondary
      - title: Python
        icon: python
        text: "\"Python has arguably become the de facto standard for exploratory, interactive, and computation-driven scientific research\"(2)"
        class: tile-secondary
    references:
      - ref: 1
        citation: "TIOBE index, https://www.tiobe.com/tiobe-index/"
      - ref: 2
        citation: "K. J. Millman and M. Aivazis, \"Python for Scientists and Engineers,\" in Computing in Science & Engineering, vol. 13, no. 2, pp. 9-12, March-April 2011, doi: 10.1109/MCSE.2011.36."
      - ref: 3
        citation: "PufahlL. et al. \"BPMN in healthcare: Challenges and best practices\", in Information Systems, vol 107, 2922"
      - ref: 4
        citation: "E S Kenne,  \"Challenges Facing Port Logistics in Cameroon, Using The Bpmn Model\", International Journal of Latest Research in Humanities and Social Science (IJLRHSS) Volume 04 - Issue 12, 2021, pp. 174-182"
      - ref: 5
        citation: "Fernandes, Jorge, João Reis, Nuno Melão, Leonor Teixeira, and Marlene Amorim. 2021. \"The Role of Industry 4.0 and BPMN in the Arise of Condition-Based and Predictive Maintenance: A Case Study in the Automotive Industry\" Applied Sciences 11, no. 8: 3438. https://doi.org/10.3390/app11083438"

  section2:
    title: A Thriving Open Source Community
    subtitle: We are open source, releasing much of our software under the LGPLv3.  We welcome contributions from the community and are happy to help you get started.  We make contributions to the open source community on a daily basis.
    features:
    - title: 1500 Stars
      text: Continuous growth and usage for over a decade, with a thriving community of contributors.
      icon: star-history.png
    - title: 42 Contributors
      text: Contributors from across the world, from the States, Germany, Sweden, South America, the Netherlands, and more.
      # Icon (from /get_started/illustrations/icons/___.svg)
      icon: contributors.png
    - title: 200 Discord Members
      text: A growing community of users and contributors, with a dedicated Discord server, and regular community calls and AMAs.
      icon: discord.png
  section3:
    title: A Powerful Low Code Platform
    subtitle: Build your first diagram in minutes. But don't let the simplicity fool you. SpiffWorkflow is a powerful platform that can handle the most complex of business processes.
    image: build_a_diagram.gif
    buttonText: Schedule a Demo
  section4:
    title: Join the Innovators
    subtitle: Join these innovators and help us continue to refine and improve this important open source project.
    clients:
    - name: Jarrad Hope
      quote: I’m proud of our investment in SpiffWorkflow. It’s in line with our mission and core principles of purposeful technology, public good, and openness. I am excited about the future and looking forward to working with you.
      job: CoFounder - Status.im
      img: jarrad
    - name: Ron Hutchins
      quote: You guys are rock stars. I really appreciate your passion and your expertise on this project. I’m very excited too about what we can do with it in the future.
      job: VP - IT - UVA
      img: ron
    - name: Demetrick Ferguson
      quote: Organizations large and small need SpiffWorkflow! SpiffWorkflow makes it possible to execute adaptable business processes that more than one person, more than one department, can understand.
      job: Portfolio Performance and Governance - Status
      img: demetrick
    - name: Brian
      quote: Spiffworkflow streamlines our execution of BPMN workflows, and its extensibility is a boon for us. The authors’ willingness to respond to our inquiries and feedback further enriches our experience with the library.
      job: CTO - Series C Startup
      img: brian2
    - name: Aleksandra Yarokhovich
      quote: Collaborating on the SpiffWorkflow project has been a delight. Passionate team, open to ideas, and a powerful product combining BPMN with Python's agility. Best wishes for its success!
      job: Business Analyst - Status
      img: sasha
  section5: true
  section6: true
  footer:
    # Logo (from /get_started/logos/___)
    logo: spiffworkflow_white.svg
    # Social Media Title
    socialmediatitle: Connect
    # Social media links (GitHub, Twitter, etc.). All are optional./
    socialmedia:
    - link: https://discord.gg/F6Kb7HNK7B
      icon: comments
    - link: https://github.com/sartography
      # Icons are from Font Awesome
      icon: github
    - link: https://www.youtube.com/channel/UCtDHzDfhyvnAb8CFmdwucUA
      icon: youtube
    - link: https://twitter.com/SpiffWorkflow
      icon: twitter
    - link: https://spiffworkflow.readthedocs.io/en/latest/index.html
      icon: book
    bulmalogo: false
    quicklinks:
      column1:
        title: "Projects"
        links:
        - text: SpiffArena
          link: /pages/spiffarena/
        - text: SpiffWorkflow
          link: /pages/spiffworkflow/
        - text: SpiffEditor
          link: /pages/spiffeditor/
      column2:
        title: "Docs"
        links:
        - text: Privacy Policy
          link: /pages/privacy_policy/
        - text: Terms of Service
          link: /pages/demo_terms_of_service/
        - text: Service Level Expectations
          link: /pages/service_level/
      column3:
        title: "Blog"
        links:
        - text: Get started
          link: /posts/articles/get_started/
        - text: Introductory Articles
          link: /posts/articles/
        - text: Deep Dives
          link: /posts/deep_dives/
